{% set name = "aws-c-compression" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7e5d7308d1dbb1801eae9356ef65558f707edf33660dd6443c985db9474725eb

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-c-compression", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - aws-c-common

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-compression${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/compression/compression.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\compression\\compression.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-compression.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-compression
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of huffman encoding/decoding

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
